---
# Setup and configure ruby for reddit app
- name: "Reddit App: Configure app env"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "Install ruby and rubygems and required packages"
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: "Install Ruby bundler"
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit app: install mongo"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: "Add mongo  repo"
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2.list

  - name: "Install mongodb"
    apt:
      allow_unauthenticated: yes
      name: mongodb-org
      state: present

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: all
  gather_facts: no

  tasks:
  - name: "Fetch app source code"
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: '~/reddit'

  - name: "Install gems by bundler"
    bundler:
      state: present
      gemfile: ~/reddit/Gemfile
...
